### ISSUE TITLE
XMLHttpRequest error in Flutter Web.

### ISSUE THREAD

**Issue by AgnelSelvan** [oiuldashov/speed_test_port#2]
Got XMLHttpRequest error(Cors Error) while running in Flutter Web

<img width="732" alt="Screenshot 2022-09-03 at 12 25 48 PM" src="https://user-images.githubusercontent.com/47639176/188259584-60627eae-7886-47dc-af49-ede5f5545b5b.png">
<img width="737" alt="Screenshot 2022-09-03 at 12 26 07 PM" src="https://user-images.githubusercontent.com/47639176/188259605-3ec7e5aa-c61b-48f5-b93c-eff5075522b4.png">

**Comment by ia-alpatov** [comment]
Hi

If you need just to debug, then use this:
`flutter run -d chrome --web-browser-flag "--disable-web-security"`

If you want to deploy, then read this https://github.com/flutter/flutter/issues/51125
